version: "3"

services:
  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - express-mongo-network-sinae
    logging:
      driver: none
  rest-api-sinae:
    hostname: rest-api-sinae
    container_name: rest-api-sinae
    depends_on: ["mongo"]
    build: ./api
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/app
      - c:/uploads:/usr/uploads
    networks:
      - express-mongo-network-sinae
    healthcheck:
        test: ["CMD", "curl", "-f", "http://mongo:27017"]
        interval: 30s
        timeout: 10s
        retries: 5               
  web-client:
    hostname: web-client
    container_name: web-client
    depends_on: ["rest-api-sinae"]
    logging:
      driver: none
    build: ./web-client
    ports:
      - "8081:80"
    networks:
      - express-mongo-network-sinae
networks: 
    express-mongo-network-sinae:
      driver: bridge

volumes:
    mongodata: