version: "3"

services:
  mongo_sinae:
    image: mongo
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - express-mongo-network-sinae
    logging:
      driver: none
  rest-api-sinae:
    hostname: rest-api-sinae
    container_name: rest-api-sinae
    depends_on: ["mongo_sinae"]
    build: ./api
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/app
      - /usr/uploads:/usr/uploads
    networks:
      - express-mongo-network-sinae
    healthcheck:
        test: ["CMD", "curl", "-f", "http://mongo:27017"]
        interval: 30s
        timeout: 10s
        retries: 5               
  web-client:
    hostname: web-client
    container_name: web-client
    depends_on: ["rest-api-sinae"]
    build: ./web-client
    ports:
      - "8080:80"
    networks:
      - express-mongo-network-sinae
    logging:
      driver: none
  site-sinae:
        hostname: site-sinae
        container_name: site-sinae
        build: ./site
        ports:
          - "80:80"
networks: 
    express-mongo-network-sinae:
      driver: bridge

volumes:
    mongodata: